<a href="https://colab.research.google.com/github/dreamjh20/Artificial-Intelligence-Study/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [ ]:
added_matrix = matrix1 + matrix2
print(added_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [ ]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [ ]:
mult_matrix = matrix1 * matrix2
print(mult_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [ ]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [ ]:
#나머지
rem_matrix = matrix1 % matrix2
print(rem_matrix)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [ ]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [ ]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [ ]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])