<a href="https://colab.research.google.com/github/dreamjh20/Artificial-Intelligence-Study/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch

scalar1 = torch.tensor([1.])
print(scalar1)


tensor([1.])


In [16]:
scalar2 = torch.tensor([2.])
print(scalar2)


tensor([2.])


In [18]:
added_scalar = scalar1+scalar2
print(added_scalar)

tensor([3.])


In [19]:
dived_scalar = scalar1 / scalar2
print(dived_scalar)

tensor([0.5000])


In [20]:
torch.add(scalar1, scalar2)

tensor([3.])

In [21]:
torch.sub(scalar1, scalar2)

tensor([-1.])

In [22]:
torch.mul(scalar1, scalar2)

tensor([2.])

In [23]:
torch.div(scalar1, scalar2)

tensor([0.5000])