<a href="https://colab.research.google.com/github/dreamjh20/Artificial-Intelligence-Study/blob/main/Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [8]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [9]:
added_vector = vector1+vector2
print(added_vector)

tensor([5., 7., 9.])


In [10]:
subed_vector = vector1 - vector2
print(subed_vector)

tensor([-3., -3., -3.])


In [11]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [12]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [13]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [14]:
torch.dot(vector1, vector2)

tensor(32.)